{% set name = "GeoAlchemy2" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GeoAlchemy2-{{ version }}.tar.gz
  sha256: 57246d44aea90b4c52f84c006f6758d0e1951eb9018f10409a87141f02159b13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - packaging
    - python >=3.7
    - sqlalchemy >=1.4

test:
  imports:
    - geoalchemy2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geoalchemy-2.readthedocs.io/en/latest/
  summary: Using SQLAlchemy with Spatial Databases
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2

extra:
  recipe-maintainers:
    - swainn
    - pmlandwehr
    - ocefpaf
    - matttriano
